home/urls.py
from nturl2path import url2pathname
from unicodedata import name
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('bio', views.bio, name='bio'),
    path('blog', views.blog, name='blog'),
    path('projects', views.projects, name='projects'),
    path(
        'detail_post/<pk>/',
        views.PostDetailView.as_view(),
        name='detail_post'
    ),
    path(
        'detail_projects/<pk>/',
        views.ProjectDetailView.as_view(),
        name='detail_project'
    ),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from django.forms import CharField
from ckeditor.fields import RichTextField


class Label(models.Model):
    name = models.CharField('Etiqueta', max_length=100, null=True, blank=True)
    backgroundColor = models.CharField('Color fondo', max_length=12, null=True, blank=True)

    class Meta:
        ordering = ['name']
        verbose_name = "Etiqueta"
        verbose_name_plural = "Etiquetas"
    
    def __str__(self):
        return (self.name)


# Create your models here.
class Post(models.Model):
    title = models.TextField('Título', max_length=300, null=True, blank=True)
    datetime = models.DateTimeField('Fecha y hora', null=True, blank=True)
    resume = models.TextField('Resume', max_length=300, null=True, blank=True)
    #text = models.TextField('Texto', max_length=12000, null=True, blank=True)
    text = RichTextField()
    image = models.ImageField('Image', null=True, blank=True, upload_to="img/")
    label = models.ManyToManyField(Label, blank=True)
    author = models.CharField('Autor', max_length=30, blank=True, null=True)
    readingTime = models.IntegerField('Tiempo lectura', blank=True, null=True)

    class Meta:
        ordering = ['-datetime']
        verbose_name = "Post"
        verbose_name_plural = "Posts"
    
    def __str__(self):
        return (self.title)

class Project(models.Model):
    title = models.TextField('Título', max_length=300, null=True, blank=True)
    datetime = models.DateTimeField('Fecha y hora', null=True, blank=True)
    resume = models.TextField('Resume', max_length=300, null=True, blank=True)
    text = models.TextField('Texto', max_length=12000, null=True, blank=True)
    image = models.ImageField('Image', null=True, blank=True, upload_to="img/")

    class Meta:
        ordering = ['-datetime']
        verbose_name = "Project"
        verbose_name_plural = "Project"
    
    def __str__(self):
        return (self.title)

home/views.py
from urllib import request
from webbrowser import get
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from .models import Post, Label, Project
from django.views.generic.detail import DetailView

def home(request):
    #return HttpResponse('Prueba')
    template = loader.get_template('index.html')
    posts = Post.objects.all()
    label = Label.objects.all()
    projects = Project.objects.all()
    context = { 'posts' : posts, 'labels': label, 'projects' : projects }
    #return render(request,'index.html', context)
    return HttpResponse(template.render(context, request))

def bio(request):
    template = loader.get_template('bio.html')
    context = {}
    return HttpResponse(template.render(context, request))

def blog(request):
    template = loader.get_template('blog.html')
    posts = Post.objects.all()
    label = Label.objects.all()
    context = { 'posts' : posts, 'labels': label, }
    return HttpResponse(template.render(context, request))


def projects(request):
    template = loader.get_template('projects.html')
    projects = Project.objects.all()
    context = { 'projects' : projects }
    return HttpResponse(template.render(context, request))

class PostDetailView(DetailView):
    model = Post
    template_name = 'post_detail.html'
    
    def get_context_data(self, **kwargs):
        name = self.kwargs['pk']
        context = super().get_context_data(**kwargs)
        context['PostsTodos'] = Post.objects.all()
        context['Post'] = Post.objects.filter(id = name)
        return context

class ProjectDetailView(DetailView):
    model = Project
    template_name = 'project_detail.html'

    def get_context_data(self, **kwargs):
        name = self.kwargs['pk']
        context = super().get_context_data(**kwargs)
        context['PostsTodos'] = Post.objects.all()
        context['Project'] = Post.objects.filter(id = name)
        return context

home/templates/base copy.html
<!doctype html>
<html lang="es">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    {% block content %}
    {% endblock %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

home/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>{% block title %}{% endblock %}</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/navbar-fixed/">

    

<!-- Bootstrap CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- Favicons -->
<!--<link rel="apple-touch-icon" href="/docs/5.1/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.1/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.1/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.1/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.1/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
<link rel="icon" href="/docs/5.1/assets/img/favicons/favicon.ico">-->
<meta name="theme-color" content="#7952b3">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="{% static 'admin/css/navbar-top-fixed.css' %}" rel="stylesheet">

    
    {% block head %} {% endblock %}
  </head>
  <body>
    
<nav class="navbar navbar-expand-md navbar-light fixed-top bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" style="color:#112240;" href="{% url 'home:home' %}"><b>Iñaki Retegi</b></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home:home' %}">HOME</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home:blog' %}">BLOG</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'home:projects' %}">PROJECTS</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'home:bio' %}">BIO</a>
        </li>
        
        <li class="nav-item">
          <a class="nav-link">CONTACTAR</a>
        </li>
      </ul>
      <!--<form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Buscar" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">BUSCADOR</button>
      </form>-->

      
    </div>
  </div>
</nav>
{% block content %} {% endblock %}
{% block bio %} {% endblock %}
{% block projects %} {% endblock %}
{% block contact %} {% endblock %}
<!--<main class="container">
  <div class="bg-light p-5 rounded">
    <h1>Navbar example</h1>
    <p class="lead">This example is a quick exercise to illustrate how fixed to top navbar works. As you scroll, it will remain fixed to the top of your browser’s viewport.</p>
    <a class="btn btn-lg btn-primary" href="/docs/5.1/components/navbar/" role="button">View navbar docs &raquo;</a>
  </div>
</main>-->


     <!-- Option 1: Bootstrap Bundle with Popper -->
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

     {% block footer %} {% endblock %}
      
  </body>

{% block outbody %} {% endblock %}
</html>

home/templates/blog.html
{% extends "base.html" %}
{% load static %}

{% block title %}****** Iñaki Retegi{% endblock %}

{% block head %}
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
crossorigin=""/>


 <!-- Make sure you put this AFTER Leaflet's CSS -->
 <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
   integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
   crossorigin=""></script>


<style>
    #map { height: 480px; }
</style>





{% endblock %}



{% block content %}
<div style="background-color:white" class="container-fluid">
    
    <div class="row">

        

        <div class="col-3 mt-3 mb-3" style="background-color:;" src="">
        </div>

        <div class="col-6 mt-3 mb-3" style="background-color:;" src="">
            <div class="row">
               
                <div class="col-12 text-left mt-5 mb-5">
                    <label style="font-size: 2rem; color:#52c6b5;" class="text">01.</label>
                    <label style="font-size: 2rem;" class="">Blog</label>
                    <hr style="font-size: 2rem;" class=""></hr>
                </div>
                {% for post in posts %}
                <div class="col-4 mt-5 mb-5">

                    <div style="min-height: 200px;" class="">
                        <a style="color:black; text-decoration: none;" href="{% url 'home:detail_post' post.id %}">
                            <img style="filter:grayscale(100%);" class="w-100" src="media/{{ post.image }}">
                        </a>
                    </div>

                    
                    <h5 style="color:#7495a6; font-size: 1rem;" class="">{{ post.datetime|date:'d-m-Y' }}</h5>
        
                    <a style="color:black; text-decoration: none;" href="{% url 'home:detail_post' post.id %}">
                        <h1 style="font-size: 1.5rem" class="">{{ post.title }}
                        </h1>
                    </a>
                    
                    <p style="font-size: 16px;" class="mt-3">
                        {{ post.resume }} <a href="">(leér más...)</a>    
                    </p>

                    <h5 style="font-size: 0.8rem;color:#52c6b5" class="">
                        {% for label in post.label.all %}
                            {% if forloop.last %}
                                {{ label }}
                            {% else %}
                                {{ label }},
                            {% endif %}
                        {% endfor %}
                    </h5>
                </div>
                
                {% endfor %}

            </div>
            
            
            </div>

            <div class="col-3 mt-3 mb-3" style="background-color:; padding-left: 5%;" src="">
                <br><br><br><h1 class="mt-5">TAGs</h1>
                {% for label in labels %}
                    <h5 style="color:#52c6b5;" class="">{{ label.name }}</h3>
                {% endfor %}
                
            </div>
    

    </div>
    
</div>

{% endblock %}





{% block footer %}
<div class="container-fluid">
    <div class="row">
        <div class="col-4 bg-dark text-center text-white"></div>
        <div class="col-4 bg-dark text-center text-white">

            <ul class="list-group list-group-flush p-5">
                <li class="bg-dark list-group-item text-white">Oiartzun</li>
                <li class="bg-dark list-group-item text-white">Euskadi</li>
                <li class="bg-dark list-group-item text-white">info@retegi.eus</li>
                <li class="bg-dark list-group-item text-white">Desarrollado por</li>
                <li class="bg-dark list-group-item text-white">Iñaki Retegi</li>
              </ul>
           
        </div>
        <div class="col-4 bg-dark text-center text-white"></div>
    </div>

</div>


{% endblock %}

{% block outbody %}



{% endblock %}

home/templates/list_track.html
{% extends "base.html" %}

{% block title %}Map {% endblock %}

{% block head %}
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
   integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
   crossorigin=""/>

<!-- Make sure you put this AFTER Leaflet's CSS -->
<script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
crossorigin=""></script>

<style>
    

</style>


{% endblock %}



{% block content %}

<div class="row">
    <div class="col-12 mt-5">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                  <th scope="col"></th>
                  <th scope="col">Nombre</th>
                  <th scope="col">Dificultad</th>
                  <th scope="col">Localidad</th>
                  <th scope="col">Provincia</th>
                  <th scope="col">Comunidad Autónoma</th>
                  <th scope="col">País</th>
                  <th scope="col">Localizar</th>
                </tr>
              </thead>
              <tbody>
                {% for track in tracks %}
                <tr>
                  <th scope="row"></th>
                  <td><a href="{% url 'home:detail_track' track.id %}">{{ track.name }}</a></td>
                  <td>{{ track.difficulty }}</td>
                  <td>{{ track.location }}</td>
                  <td>{{ track.province }}</td>
                  <td>{{ track.autonomous_community }}</td>
                  <td>{{ track.country }}</td>
                  <td><a href="https://maps.google.com/?ll={{ track.longitud }},{{ track.latitude }}&z=18&t=p">localizar</a></td>
                  
                </tr>
                {% endfor %}
              </tbody>
          </table>
    </div>
</div>
{% for track in tracks %}
{% endfor %}







{% endblock %}

{% block outbody %}
{% endblock %}

home/templates/post_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}****** Iñaki Retegi{% endblock %}

{% block head %}
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
crossorigin=""/>


 <!-- Make sure you put this AFTER Leaflet's CSS -->
 <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
   integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
   crossorigin=""></script>


<style>
    #map { height: 480px; }
</style>





{% endblock %}



{% block content %}
<div class="container">
    
    <div class="row">

        <div class="col-1 mt-5 mb-3" style="background-color:;" src="">
        </div>

        <div class="col-7 mt-5 mb-3">
            <h1 style="font-size: 4rem" class="mt-5">{{ post.title }}</h1>
            <a style="text-decoration:none;color:black" href="{% url 'home:blog' %}"><b>blog</b></a><br>
            <label class="mt-2">Actualizado: <b>{{ post.datetime|date:'d-m-Y' }}</b></label>    <label style="margin-left: 50px">Autor: <b>{{ post.author }}</b></label>    <label style="margin-left: 50px">Tiempo estimado:<b>{{ post.readingTime }}min</b></label>
            <img class="w-100 mt-3" src="/media/{{ post.image }}">
            
            <p class="mt-4">{{ post.text|safe }}</p>
            <label class="mt-2 text-right">Actualizado: <b>{{ post.datetime|date:'d-m-Y' }}</b></label>
            
           
        </div>

        <div class="col-3 mt-5 mb-3" style="background-color:;" src="">
            <h1 style="font-size: 2rem" class="mt-5">Tabla de contenidos</h1>
            <hr></hr>
            {% for post in PostsTodos %}
                <a style="text-decoration:none;" href=""><h3 class="mt-3" style="font-size: 1rem; color:#52c6b5">{{ post.title}}</h3></a>
            {% endfor %}

        </div>

        <div class="col-1 mt-5 mb-3 text-center" style="background-color:;" src="">
            
            
        </div>

    </div>
    
</div>

{% endblock %}





{% block footer %}
<div class="container-fluid">
    <div class="row">
        <div class="col-4 bg-dark text-center text-white"></div>
        <div class="col-4 bg-dark text-center text-white">

            <ul class="list-group list-group-flush p-5">
                <li class="bg-dark list-group-item text-white">Oiartzun</li>
                <li class="bg-dark list-group-item text-white">Euskadi</li>
                <li class="bg-dark list-group-item text-white">info@retegi.eus</li>
                <li class="bg-dark list-group-item text-white">Desarrollado por</li>
                <li class="bg-dark list-group-item text-white">Iñaki Retegi</li>
              </ul>
           
        </div>
        <div class="col-4 bg-dark text-center text-white"></div>
    </div>

</div>


{% endblock %}

{% block outbody %}



{% endblock %}

home/templates/project_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}****** Iñaki Retegi{% endblock %}

{% block head %}
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
crossorigin=""/>


 <!-- Make sure you put this AFTER Leaflet's CSS -->
 <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
   integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
   crossorigin=""></script>


<style>
    #map { height: 480px; }
</style>





{% endblock %}



{% block content %}
<div class="container">
    
    <div class="row">

        <div class="col-1 mt-5 mb-3" style="background-color:;" src="">
        </div>

        <div class="col-7 mt-5 mb-3">
            <h1 style="font-size: 4rem" class="mt-5">{{ project.title }}</h1>
            <a style="text-decoration:none;color:black" href="{% url 'home:projects' %}"><b>project</b></a><br>
            <!--<label class="mt-2">Actualizado: <b>{{ project.datetime|date:'d-m-Y' }}</b></label>    <label style="margin-left: 50px">Autor: <b>{{ project.author }}</b></label>    <label style="margin-left: 50px">Tiempo estimado:<b>{{ project.readingTime }}min</b></label>-->
            <img class="w-100 mt-3" src="/media/{{ project.image }}">
            
            <p class="mt-4">{{ project.text }}</p>
            <!--<label class="mt-2 text-right">Actualizado: <b>{{ project.datetime|date:'d-m-Y' }}</b></label>-->
            
           
        </div>

        <div class="col-3 mt-5 mb-3" style="background-color:;" src="">
            <h1 style="font-size: 2rem" class="mt-5">Tabla de contenidos</h1>
            <hr></hr>
            {% for post in ProjectTodos %}
                <a style="text-decoration:none;" href=""><h3 class="mt-3" style="font-size: 1rem; color:#52c6b5">{{ project.title}}</h3></a>
            {% endfor %}

        </div>

        <div class="col-1 mt-5 mb-3 text-center" style="background-color:;" src="">
            
            
        </div>

    </div>
    
</div>

{% endblock %}





{% block footer %}
<div class="container-fluid">
    <div class="row">
        <div class="col-4 bg-dark text-center text-white"></div>
        <div class="col-4 bg-dark text-center text-white">

            <ul class="list-group list-group-flush p-5">
                <li class="bg-dark list-group-item text-white">Oiartzun</li>
                <li class="bg-dark list-group-item text-white">Euskadi</li>
                <li class="bg-dark list-group-item text-white">info@retegi.eus</li>
                <li class="bg-dark list-group-item text-white">Desarrollado por</li>
                <li class="bg-dark list-group-item text-white">Iñaki Retegi</li>
              </ul>
           
        </div>
        <div class="col-4 bg-dark text-center text-white"></div>
    </div>

</div>


{% endblock %}

{% block outbody %}



{% endblock %}

home/templates/projects.html
{% extends "base.html" %}
{% load static %}

{% block title %}****** Iñaki Retegi{% endblock %}

{% block head %}
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
crossorigin=""/>


 <!-- Make sure you put this AFTER Leaflet's CSS -->
 <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
   integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
   crossorigin=""></script>


<style>
    #map { height: 480px; }
</style>





{% endblock %}



{% block projects %}
<div style="background-color:white" class="container-fluid">
    
    <div class="row">

        

        <div class="col-3 mt-3 mb-3" style="background-color:;" src="">
        </div>

        <div class="col-6 mt-3 mb-3" style="background-color:;" src="">
            <div class="row">
               
                <div class="col-12 text-left mt-5 mb-5">
                    <label style="font-size: 2rem; color:#52c6b5;" class="text">03.</label>
                    <label style="font-size: 2rem;" class="">Projects</label>
                    <hr style="font-size: 2rem;" class=""></hr>
                </div>
                {% for project in projects %}
                <div class="col-4 mt-5 mb-5">

                    <div style="min-height: 200px;" class="">
                        <a style="color:black; text-decoration: none;" href="{% url 'home:detail_project' project.id %}">
                        <img style="filter:grayscale(100%);" class="w-100" src="media/{{ project.image }}">
                        </a>
                        
                    </div>

                    
                    <h5 style="color:#7495a6; font-size: 1rem;" class="">{{ project.datetime|date:'d-m-Y' }}</h5>
        
                    <a style="color:black; text-decoration: none;" href="{% url 'home:detail_project' project.id %}">
                        <h1 style="font-size: 1.5rem" class="">{{ project.title }}
                        </h1>
                    </a>
                    
                    <p style="font-size: 16px;" class="mt-3">
                        {{ project.resume }} <a href="">(leér más...)</a>    
                    </p>

                    <h5 style="font-size: 0.8rem;color:#52c6b5" class="">
                        {% for label in project.label.all %}
                            {% if forloop.last %}
                                {{ label }}
                            {% else %}
                                {{ label }},
                            {% endif %}
                        {% endfor %}
                    </h5>
                </div>
                
                {% endfor %}

            </div>
            
            
            </div>

        <div class="col-3 mt-3 mb-3" style="background-color:; padding-left: 5%;" src="">
            <h1 class="mt-5">TAGs</h1>
            {% for label in labels %}
                <h5 style="color:{{ label.backgroundColor }};" class="">{{ label.name }}</h3>
            {% endfor %}
            
        </div>

    </div>
    
</div>

{% endblock %}





{% block footer %}
<div class="container-fluid">
    <div class="row">
        <div class="col-4 bg-dark text-center text-white"></div>
        <div class="col-4 bg-dark text-center text-white">

            <ul class="list-group list-group-flush p-5">
                <li class="bg-dark list-group-item text-white">Oiartzun</li>
                <li class="bg-dark list-group-item text-white">Euskadi</li>
                <li class="bg-dark list-group-item text-white">info@retegi.eus</li>
                <li class="bg-dark list-group-item text-white">Desarrollado por</li>
                <li class="bg-dark list-group-item text-white">Iñaki Retegi</li>
              </ul>
           
        </div>
        <div class="col-4 bg-dark text-center text-white"></div>
    </div>

</div>


{% endblock %}

{% block outbody %}



{% endblock %}